tls:
  options:
    default:
      minVersion: VersionTLS13 # Minimum TLS Version
      sniStrict: true # Strict Server Name Indication (SNI) checking
      curvePreferences:
        - CurveP521
        - CurveP384
      cipherSuites:
        - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256
