---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/docker/

# Adapt name, host and port as needed
tab1-docker:
  host: 192.168.22.11
  port: 2375

# my-docker:
#   host: 127.0.0.1
#   port: 2375

# my-docker:
#   socket: /var/run/docker.sock
