services:
  litellm:
    image: docker.litellm.ai/berriai/litellm:main-latest
    restart: unless-stopped
    ports:
      - 44000:4000
    environment:
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASS}@ltl-db:5432/${DB_NAME}
      STORE_MODEL_IN_DB: "True" # allows adding models to proxy via UI
      LITELLM_MASTER_KEY: ${LITELLM_MASTER_KEY}
      LITELLM_SALT_KEY: ${LITELLM_SALT_KEY}
    depends_on:
      - ltl-db # Indicates that this service depends on the 'ltl-db' service, ensuring it starts first
    healthcheck:
      # Defines the health check configuration for the container
      test:
        - CMD-SHELL
        - python3 -c "import urllib.request;
          urllib.request.urlopen('http://localhost:4000/health/liveliness')" # Command to execute for health check
      interval: 30s # Perform health check every 30 seconds
      timeout: 10s # Health check command times out after 10 seconds
      retries: 3 # Retry up to 3 times if health check fails
      start_period: 40s # Wait 40 seconds after container start before beginning health checks
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - traefik.enable=true
      - traefik.http.routers.ltl.entrypoints=https
      - traefik.http.routers.ltl.rule=Host(`ltl.example.com`)
      - homepage.name=LiteLLM
      - homepage.group=foo_apps
      - homepage.icon=https://github.com/BerriAI/litellm/blob/main/docs/my-website/img/favicon.png?raw=true
      - homepage.href=https://ltl.example.com/ui
      - homepage.description=LiteLLM (foo)

  ltl-db:
    image: postgres:16
    restart: always
    container_name: litellm_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -d ${DB_NAME} -U ${DB_USER}
      interval: 1s
      timeout: 5s
      retries: 10
    labels:
      - com.centurylinklabs.watchtower.enable=true
