job: extension
config:
  name: flux_dev-tok
  process:
  - type: sd_trainer
    training_folder: ../trained_LoRA
    device: cuda:0
    trigger_word: tok
    network:
      type: lora
      linear: 16
      linear_alpha: 16
    save:
      dtype: float16
      save_every: 250
      max_step_saves_to_keep: 4
      push_to_hub: false
    datasets:
    - folder_path: ../training_images-tok
      caption_ext: txt
      caption_dropout_rate: 0.05
      shuffle_tokens: false
      cache_latents_to_disk: true
      resolution:
      - 512
      - 768
      - 1024
    train:
      batch_size: 1
      steps: 4000
      gradient_accumulation_steps: 1
      train_unet: true
      train_text_encoder: false
      gradient_checkpointing: true
      noise_scheduler: flowmatch
      optimizer: adamw8bit
      lr: 0.0001
      ema_config:
        use_ema: true
        ema_decay: 0.99
      dtype: bf16
    model:
      name_or_path: black-forest-labs/FLUX.1-dev
      is_flux: true
      quantize: true
    sample:
      sampler: flowmatch
      sample_every: 250
      width: 1024
      height: 1024
      prompts:
      - a woman holding a sign that says, 'this is a sign'
      - 'a [trigger] man holding a sign that says ''I LOVE PROMPTS!'''
      - 'a [trigger] man holding a sign that says ''AI is fun'''
      - a [trigger] man as a Jedi warrior, deep blue lightsaber, dark purple background
        with some multicolor neon light reflecting
      - a [trigger] man as a green lantern, cosmic background, creating a dragon from
        his ring, majestic, rule of third
      - a [trigger] man as Conan the barbarian, snow-covered fields, sword in hand,
        defiant, dynamic pose, golden ratio, asymmetric composition, photorealism,
        cinematic realism
      - a portrait of a [trigger] man as Superman flying in space, yellow sun in the
        background, majestic, comic style
      - a [trigger] man as a cyberpunk warrior, anime style
      - professional photograph portrait of a [trigger] man, black and white
      - a [trigger] man wearing sunglasses riding a high-speed motorbike, hyper-maximalist,
        octane render
      - a [trigger] man, lucid dream-like 3d model, game asset, blender, unreal engine,
        rule of thirds, wide angle shot, looking off in distance style, glowing background,
        vivid neon wonderland, particles, blue, green, orange
      neg: ''
      seed: 42
      walk_seed: true
      guidance_scale: 4
      sample_steps: 20
meta:
  name: flux_dev-tok
  version: '1.0'
