# To see all available options, please visit the docs:
# https://docs.digpangolin.com/self-host/advanced/config-file 

gerbil:
    start_port: 51820
    base_endpoint: "pangolin.example.com"

app:
    dashboard_url: "https://pangolin.example.com"
    log_level: "info"
    telemetry:
        anonymous_usage: false
    save_logs: true
    log_failed_attempts: true

domains:
    domain1:
        base_domain: "example.com"
        cert_resolver: "letsencrypt"
        prefer_wildcart_cert: true

server:
    secret: "REPLACE_WITH_SECRET"
    cors:
        origins: ["https://pangolin.example.com"]
        methods: ["GET", "POST", "PUT", "DELETE", "PATCH"]
        allowed_headers: ["X-CSRF-Token", "Content-Type"]
        credentials: false

email:
    smtp_host: "smtp.fastmail.com"
    smtp_port: 587
    smtp_user: "REPLACE_WITH_FASTMAIL_USER"
    smtp_pass: "REPLACE_WITH_FASTMAIL_APP_PASSWORD"
    no_reply: "REPLACE_WITH_NO_REPLY_EMAIL"

flags:
    require_email_verification: true
    disable_signup_without_invite: true
    disable_user_create_org: true
    allow_raw_resources: true
